config/routes.rb
Rails.application.routes.draw do
  root 'hellos#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :tags
  resources :posts do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :post

  validates :name, presence: true, length: { maximum: 20 }
  validates :website, length: { maximum: 64}
  validates :body, presence: true, length: { maximum: 164 }
end

app/models/hello.rb
class Hello < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base

  extend FriendlyId
  friendly_id :title, use: :slugged

  has_many :post_tags
  has_many :tags, through: :post_tags

  has_many :comments

  paginates_per 3

end

app/models/post_tag.rb
class PostTag < ActiveRecord::Base

  belongs_to :post
  belongs_to :tag

end

app/models/tag.rb
class Tag < ActiveRecord::Base

  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :post_tags
  has_many :posts, through: :post_tags
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # load_and_authorize_resource
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new(comment_params)
  end

  def create
    @post = Post.friendly.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    if @comment.save
      flash[:notice] = "Yorumunuz başarıyla kaydedildi. Onay beklemektedir.."
      redirect_to post_path(@post)
    else
      flash[:alert] = "Yorumunuz kaydedilemedi. Lütfen boş alanları dikkatli bir şekilde doldurunuz."
      redirect_to post_path(@post)
    end
  end

  private
  def comment_params
      params.require(:comment).permit(:name, :website, :body, :check)
  end
end

app/controllers/hellos_controller.rb
class HellosController < ApplicationController

  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show]
  before_action :set_hello, only:[:index, :show]

  def index
    @color = "#123456"
    @tags = Tag.all
    @posts = Post.all.order("created_at desc").page params[:page]
    respond_to do |format|
      format.html
      format.rss { render :layout => false }
    end
  end

  def show
    @comments = @post.comments
    @tags = @post.tags
  end

  private
  def set_post
    @post = Post.friendly.find(params[:id])
  end

  def set_hello
    @hellos = Hello.limit(1).order("RANDOM()")
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show]

  def show
    @posts = @tag.posts.order("posts.created_at desc").page params[:page]
  end

  private
  def set_tag
    @tag = Tag.friendly.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hellos_helper.rb
module HellosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<div id="yorum", class="modal bottom-sheet" >
  <div class="modal-content">
  <%= form_for ([@post, @post.comments.build]) do |f| %>
  <div class="input-field col s12 m12 l3">
    <%= f.text_field :name, id:"name", length:"20" %>
    <%= f.label "İsmin*", for:"name" %>
  </div>
  <div class="input-field col s12 m12 l3">
    <%= f.text_field :website, id:"website", type:"url", class:"validate" %>
    <%= f.label "Blog veya linkedin adresin", for:"website" %>
  </div>
  <div class="input-field col s12 m12 l3">
    <%= f.text_field :body, id:"comment", length:"164" %>
    <%= f.label "Yorumun*", for:"comment" %>
  </div>
  <div class="col s12 m12 l3">
    <button class="btn waves-effect" name="action" type="submit"><i class="material-icons" style="font-size:2.1rem;">&#xE163;</i></button><br>
  </div>
  <% end %>
  </div>
</div>

app/views/hellos/index.html.erb
<% content_for :title, "Merhaba!" %>
<% content_for :description, "Blog" %>
  <div class="row">
    <div class="post" id="home-hi">
      <div class="hi">
          &larr;hello, bonjour, سلام, hei, γεια σας, ciao, hola, привет&rarr;
      </div>
    </div>
    <div class="col s4 m4 l4">
      <div class="post" id="home-post" style="height: 320px;">
      <center><br>
        <%= link_to root_path do %>
      <div class="profile waves-effect"></div>
      <% end %>
      </center><br>
    </div>
  </div>
    <div class="col s8 m8 l8">
      <div class="post" id="home-post" style="opacity:0.9;height: 320px;">
      <p>
      Statham's life in the media began when he was spotted by the agency Sports
       Promotions specialising in sports modelling while he was training at London's Crystal
        Palace National Sports Centre. Afterwards, he became a model for the clothing brand
         French Connection. A spokesperson for the high street clothing chain said:
          "We chose Jason because we wanted our model to look like a normal guy. His look is just
           right for now: very masculine and not too male-modelly."However, he was still forced
            to follow in his father's footsteps as a street seller to make ends meet, selling
             "fake perfume and jewellery on street corners...
      </p>
      <div class="row">
        <center>
        <div class="col s12 m12 l12" id="info">
        <a href="https://linkedin.com" target="_blank"><i class="material-icons" id="home-icons-font">&#xE0AF;</i></a>
        <a href="https://github.com" target="_blank">  <i class="material-icons" id="home-icons-font">&#xE86F;</i></a>
        <a href="https://twitter.com" target="_blank">  <i class="material-icons" id="home-icons-font">&#xE853;</i></a>
        </div>
        </center>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% set_meta_tags title: yield(:title) %>
    <% set_meta_tags description: yield(:description) %>
    <title><%= yield(:title) %></title>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= auto_discovery_link_tag :rss, posts_url(:format => :rss) %>
    <%= csrf_meta_tags %>
    <link href='https://fonts.googleapis.com/css?family=ABeeZee|Montserrat|Oxygen:400' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
     <%= favicon_link_tag 'favicon.ico' %>
  </head>
    <body>
      <div class="wrapper">
        <div class="row" id="nav">
          <div class="col s10 m10 l10">
            <div class="page-title">
              <% if (yield(:title)).length > 27 %>
              <%= (yield(:title)).first(28) %>...
              <% else %>
              <%= yield(:title) %>
              <% end %>
            </div>
          </div>
          <div class="col s1 m1 l1">
            <%= link_to posts_path do %>
            <span class="btn-floating btn-large waves-effect waves-light lime">
              <i class="material-icons" id="app-icons-font">&#xE8D2;</i></span>
              <% end %>
          </div>
          <div class="col s1 m1 l1">
            <%= link_to root_path do %>
            <span class="btn-floating btn-large waves-effect waves-light light-green">
              <i class="material-icons" id="app-icons-font">&#xE88A;</i></span>
              <% end %>
          </div>
      </div>
        <div class="row">
          <% if flash[:alert] %>
            <div class="alert"><%= flash[:alert] %></div>
          <% end %>
          <% if flash[:notice] %>
            <div class="notice"><%= flash[:notice] %></div>
          <% end %>
          <div class="se-pre-con"></div>
        <%= yield %>
        </div>
        <div class="push"></div>
    </div>
    <div class="footer">
    <footer>
      <div class="line z-depth-1"></div>
    <a href="https://github.com/rails/rails"> Ruby on Rails </a>| Copyleft 2015 |<a href="https://github.com/Dogfalo/materialize"> Materialize Css </a>
      </div>
    </footer>
    <a href="#" class="scrollToTop waves-effect btn-floating btn-large"><i class="material-icons" id="plane">&#xE53D;</i></a>
  </body>
</html>

app/views/posts/_list.html.erb
<div class="row">
<% @hellos.each do |hello| %>
  <div class="col s12 m12 l12">
    <div class="words">
      <%= hello.words %>
    </div>
  </div>
<% end  %>
</div>
<% @posts.each do |post| %>
  <div class="col s12 m12 l12">
    <div class="post">
        <div class="parallax-container" style="border-bottom-color:<%="#{post.color}"%>;">
      <div class="parallax">
        <%= image_tag(post.image) %>
      </div>
    </div>
    <%= link_to (post_path(post)) do %>
    <div class="btn-floating btn-large waves-effect" style="margin-top:-38px;">
      <i class="material-icons" id="post-index-continue">&#xE037;</i>
    </div>
    <% end %>
    <div class="title" id="post-index-title">
      <% if (post.title).length > 40 %>
      <%= (post.title).first(41) %>...
      <% else %>
      <%= post.title %>
      <% end %>
    </div>
    <div class="row">
      <div class="col s2 m2 l2">
        <div class="post-bar">
        <center>
          <i class="material-icons" id="post-index-icons">&#xE192;</i><br>
          <%= (post.created_at).strftime("%d %B")%><br>
        </center>
        </div>
      </div>
      <div class="col s10 m10 l10">
        <%= raw post.body.first(340) %>...
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/posts/index.html.erb
<% content_for :title, "Yazılarım" %>
<% content_for :description, "Yazılar ve Paylaşımlar" %>
<div class="col s10 m10 l10">
  <%= render 'list' %>
  <div class="row">
    <div class="col s12 m12 l12">
      <center>
        <b>
          <%= link_to_previous_page @posts, 'Gerİ', class:"btn waves-effect" %>
        </b>
        <b>
          <%= link_to_next_page @posts, 'İlerİ', class:"btn waves-effect" %>
        </b>
      </center>
    </div>
  </div>
</div>
<%= render 'tags/list' %>

app/views/posts/show.html.erb
<% content_for :title, @post.title %>
<% content_for :description, (@post.body.first(160)).html_safe %>
<div  class="row">
<div class="col s12 m12 l12">
  <div class="post" style="font-size:18px;">
    <div class="card-content z-depth-1" id="card-bar">
      <div class="row" style="padding-bottom:10px;">
        <div class="col s5 m5 l5">
        <span style="font-size:13px;color:#fff;"><%= @post.title %></span>
        </div>
      <div class="col s2 m2 l2">
        <center id="card-bar-font">
          <i class="material-icons" style="font-size:1.4rem;">&#xE192;</i>
          <%= (@post.created_at).strftime("%d %B") %>
        </center>
      </div>
      <div class="col s3 m3 l3">
        <center id="card-bar-font">
          <% @tags.each do |tag| %>
            <i class="material-icons" style="font-size:1.4rem;">&#xE54E;</i>
            <%= link_to tag.name, tag_path(tag) %>&nbsp;&nbsp;
          <% end %>
        </center>
      </div>
      <div class="col s2 m2 l2">
        <span style="padding-top:5px;"><%= social_share_button_tag(@post.title) %></span>
      </div>
    </div>
  </div>
  <div class="parallax-container" id="post-show-image">
    <div class="parallax">
      <%= image_tag(@post.image) %>
    </div></div>
  <%= raw @post.body %>
  </div>
  <%= render 'comments/form' %>
  <center>
    <a class="waves-effect waves-light btn modal-trigger" href="#yorum">
      <b>Yorumla</b>
    <i class="material-icons right" style="font-size:1.1rem;">&#xE0B9;</i></a>
  </center>
</div>

<% @comments.each do |comment| %>
<% if comment.chech?  %>
<div class="col s4 m4 l4">
  <div class="card">
      <div class="card-content white-text">
        <span class="card-title">
          <center>
            <%= link_to comment.name, comment.website %>
          </center>
        </span>
        <div class="time">
          <div class="row" style="opacity:0.85;">
            <div class="col s1 m1 l1">&nbsp;</div>
            <div class="col s5 m5 l5">
              <center>
                <i class="material-icons" style="font-size:1.64rem;">&#xE192;</i><br>
                <%= (comment.created_at).strftime("%d %B") %>
              </center>
            </div>
            <div class="col s5 m5 l5">
              <center>
                <i class="material-icons" style="font-size:1.64rem;">&#xE7FD;</i><br>
                @<%= (((comment.name.first(14)).gsub(/[ĞğŞşİıÇçÖöÜü]/, 'Ğ' => 'g', 'ğ' => 'g', 'Ş' => 's', 'ş' => 's', 'İ' => 'i', 'ı' => 'i', 'Ç' => 'c', 'ç' => 'c', 'Ö' => 'o', 'ö' => 'o', 'Ü' => 'u', 'ü' => 'u')).delete(' ')).downcase  %>
              </center>
            </div>
            <div class="col s1 m1 l1">&nbsp;</div>
          </div>
          <span style="font-size:16px;">
            <%= comment.body %>
          </span>
        </div>
      </div>
    </div>
  </div>
  <% elsif @comments.count < 1 %>
  <div class="col s12 m12 l12">
    <div class="card">
      <span class="card-title">
        <center style="padding:3px;">
          Henüz bir yorum yok. Fakat olsun istiyorsan fikrini belirtebilirsin. Bekliyorum.
        </center>
      </span>
    </div>
  </div>
  <% end %>
<% end %>
</div>

app/views/tags/_list.html.erb
<% @tags.each do |tag| %>
<div class="col s2 m2 l2">
  <div class="card" style="padding:10px;">
      <span class="card-title" id="tag-card-title">
          <i class="material-icons left" id="tag-card-icons">&#xE54E;</i>
          <%= link_to tag_path(tag) do %>
          <%= tag.name %>
          <% end %>
      </span>
  </div>
</div>
<% end %>

app/views/tags/show.html.erb
<% content_for :title, "#{@tag.name} etiketi" %>
<% @posts.each do |post| %>
<div class="col s6 m6 l6">
  <div class="post" id="post">
        <div class="parallax-container" id="tag-show-parallax" style="border-bottom-color: <%="#{post.color}"%>;">
      <div class="parallax">
        <%= image_tag(post.image) %>
      </div>
    </div>
    <%= link_to (post_path(post)) do %>
      <div class="btn-floating btn-large waves-effect" style="margin-top:-32px;margin-left:364px;"><i class="material-icons" id="tag-index-continue">&#xE037;</i></div>
    <% end %>
    <div class="title" id="tag-post-title">
      <div class="row">
        <div class="col s3 m3 l3">
          <div class="time">
            <center>
              <i class="material-icons" style="font-size:1.8rem;">&#xE192;</i><br>
              <%= (post.created_at).strftime("%d %B") %>
            </center>
          </div>
        </div>
        <div class="col s9 m9 l9">
        <% if (post.title).length > 47 %>
          <%= (post.title).first(48) %>...
        <% else %>
          <%= post.title %>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>
<% end %>
</div>